### PR TITLE
Fix a mistype on switch word

### PR DESCRIPTION
**Pull request by joelrfcosta**
I think you meant to use `switch` here :)

### CODE REVIEW

**Comment by arielelkin** [comment]
Thanks @joelrfcosta

**Comment by joelrfcosta** [comment]
No problem @arielelkin. Great article btw 👍

**Comment by arielelkin** [comment]
btw, if you're gonna send a pull request to a static site, it'll always be easier for you (and for the repo maintainer) if you send it to the repository with the markdown :-) 

So after I merged your PR, I had to manually update the markdown repo like so:
https://github.com/arielelkin/site_source/commit/08d90e4c8c52b85b6b4c9e03010a5654614b0afe

if you send the PR directly to the markdown, it's easier for you to do, for me to review, and to then build and push the repo.

**Comment by joelrfcosta** [comment]
Makes sense. Always learning, thanks! :)

**Pull request merged**
